name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Run Ruff
        run: ruff format --diff --output-format=github .

